In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
#class practice

[1 2 3 4 5]


In [2]:
#Question 1
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr1)
print("Addition of 2:", arr1 + 2)
print("Multiply by 3:", arr1 * 3)
print("Divide by 2:", arr1 / 2)

Original Array: [1 2 3 4 5]
Addition of 2: [3 4 5 6 7]
Multiply by 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
#2 a
import numpy as np
arr2 = np.array([1, 2, 3, 6, 4, 5])
print("Original Array:", arr2)
print("Reversed Array:", arr2[::-1])

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


In [10]:
#2 b
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

def most_frequent(arr):
  values, counts = np.unique(arr, return_counts=True)
  max_count_index = np.argmax(counts)
  most_frequent_value = values[max_count_index]
  indices = np.where(arr == most_frequent_value)[0]
  return most_frequent_value, indices

most_frequent_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {most_frequent_x}, indices: {indices_x}")

most_frequent_y, indices_y = most_frequent(y)
print(f"Most frequent value in y: {most_frequent_y}, indices: {indices_y}")

Most frequent value in x: 1, indices: [0 5 7 8 9]
Most frequent value in y: 1, indices: [0 1 2]


In [12]:
#3
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
a = arr[0, 1]
b = arr[2, 0]
print("Element at 1st row, 2nd column:", a)
print("Element at 3rd row, 1st column:", b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [7]:
#4
import numpy as np
K=np.linspace(10,100,10)
print("Array:",K)
print("Dimensions:",K.ndim)
print("Shape:", K.shape)
print("Total elements:", K.size)
print("Data type:", K.dtype)
print("Total bytes consumed:", K.nbytes)
transpose = K.reshape(10, 1)
print("Transposed Array:\n", transpose)
print("We cannot use T attribute because T attribute works on 2-D arrays.")



Array: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Dimensions: 1
Shape: (10,)
Total elements: 10
Data type: float64
Total bytes consumed: 80
Transposed Array:
 [[ 10.]
 [ 20.]
 [ 30.]
 [ 40.]
 [ 50.]
 [ 60.]
 [ 70.]
 [ 80.]
 [ 90.]
 [100.]]
We cannot use T attribute because T attribute works on 2-D arrays.


In [8]:
#5
import numpy as np
ucs420_kinjal = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_kinjal))
print("Median:", np.median(ucs420_kinjal))
print("Max:", np.max(ucs420_kinjal))
print("Min:", np.min(ucs420_kinjal))
print("Unique Elements:", np.unique(ucs420_kinjal))
reshaped_ucs420_kinjal = ucs420_kinjal.reshape(4, 3)
print("Reshaped Array:\n", reshaped_ucs420_kinjal)
resized_ucs420_kinjal = np.resize(ucs420_kinjal, (2, 3))
print("Resized Array:\n", resized_ucs420_kinjal)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [40 50 60]]
